version: '3.9'
services:
  mern-blog:
    container_name: mern_blog
    restart: always
    build:
      context: ./
    ports:
      - "5555:5555"
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - JWT_SECRET=mynameissiat
    command: 
      - npm
      - run 
      - dev